# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM ubuntu:latest AS build-env
WORKDIR /app

# Instal Tes Compliance
RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt install -y software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get -y install python3.8 python3.8-distutils python3-pip jq git

RUN git clone https://github.com/elixir-cloud-aai/tes-compliance-suite.git 

WORKDIR /app/tes-compliance-suite
RUN python3.8 setup.py install

RUN mkdir results

COPY entrypoint.sh /app/tes-compliance-suite/entrypoint.sh

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]