name: snakemake-tes-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - pip
  - snakemake
  - azure-identity
  - pip:
    - azure-storage-blob==12.23.1
    - future==1.0.0
    - isodate==0.6.1
    - bwa=0.7.18
    - py-tes
    - snakemake-executor-plugin-tes==0.1.3
    - snakemake-storage-plugin-azure==0.4.2