# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Restore packages in separate layer
COPY CommonUtilities/CommonUtilities.csproj CommonUtilities/
COPY Tes/Tes.csproj Tes/
COPY TesApi.Web/TesApi.Web.csproj TesApi.Web/

# Copy the rest of the files and publish
COPY . ./
RUN dotnet publish -c Release /p:PublishDir=/app/out TesApi.Web/TesApi.Web.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .
RUN apt update && apt full-upgrade -y && apt autoremove -y
RUN adduser --home /home/tes -u 1000 tes
RUN apt install -y libcap2-bin
RUN setcap CAP_NET_BIND_SERVICE=+eip /usr/share/dotnet/dotnet
ENTRYPOINT ["dotnet", "tesapi.dll"]
