# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled
WORKDIR /app
COPY . ./
RUN apt update && apt full-upgrade -y && apt autoremove -y
RUN adduser --home /home/tes -u 1000 tes
RUN apt install -y libcap2-bin
RUN setcap CAP_NET_BIND_SERVICE=+eip /usr/share/dotnet/dotnet
ENTRYPOINT ["dotnet", "tesapi.dll"]
