apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tes
  name: tes
spec:
  ports:
    - name: {{ .Values.service.tesPort | quote }}
      port: {{ .Values.service.tesPort }}
      targetPort: {{ .Values.service.tesPort }}
  selector:
    io.kompose.service: tes
status:
  loadBalancer: {}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: tes-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tes
                port:
                  number: {{ .Values.service.tesPort }}