apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tes
  name: tes
spec:
  ports:
    - name: {{ .Values.service.tesPort | quote }}
      port: {{ .Values.service.tesPort }}
      targetPort: {{ .Values.service.tesPort }}
  selector:
    io.kompose.service: tes
status:
  loadBalancer: {}
