apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tes
    aadpodidbinding: {{ .Values.identity.name }}
  name: tes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tes
        aadpodidbinding: {{ .Values.identity.name }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/tes: runtime/default
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups: [1000]
      terminationGracePeriodSeconds: 90
      containers:
        - env:
            - name: TesPostgreSql__ServerName
              value: {{ .Values.tesDatabase.serverName }}
            - name: TesPostgreSql__ServerNameSuffix
              value: {{ .Values.tesDatabase.serverNameSuffix }}
            - name: TesPostgreSql__ServerSslMode
              value: {{ .Values.tesDatabase.serverSslMode }}
            - name: TesPostgreSql__ServerPort
              value: {{ .Values.tesDatabase.serverPort | quote }}
            - name: TesPostgreSql__DatabaseName
              value: {{ .Values.tesDatabase.databaseName }}
            - name: TesPostgreSql__DatabaseUserLogin
              value: {{ .Values.tesDatabase.databaseUserLogin }}
            - name: TesPostgreSql__DatabaseUserPassword
              value: {{ .Values.tesDatabase.databaseUserPassword }}
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:{{ .Values.service.tesPort }}/
            - name: Storage__DefaultAccountName
              value: {{ .Values.persistence.storageAccount }}
            - name: AzureServicesAuthConnectionString
              value: {{ .Values.config.azureServicesAuthConnectionString }}
            - name: ApplicationInsightsAccountName
              value: {{ .Values.config.applicationInsightsAccountName }}
            - name: AzureOfferDurableId
              value: {{ .Values.config.azureOfferDurableId }}
            - name: BatchAccount__AccountName
              value: {{ .Values.config.batchAccountName }}
            - name: BatchNodes__SubnetId
              value: {{ .Values.config.batchNodesSubnetId }}
            - name: NodeImages__Blobxfer
              value: {{ .Values.config.blobxferImageName }}
            - name: BatchNodes__DisablePublicIpAddress
              value: {{ .Values.config.disableBatchNodesPublicIpAddress | quote }}
            - name: BatchScheduling__Disable
              value: {{ .Values.config.disableBatchScheduling | quote }}
            - name: NodeImages__Docker
              value: {{ .Values.config.dockerInDockerImageName }}
            - name: BatchScheduling__UseLegacyAutopools
              value: {{ .Values.config.useLegacyBatchImplementationWithAutopools | quote }}
            - name: BatchImageGen1__Offer
              value: {{ .Values.config.gen2BatchImageOffer }}
            - name: BatchImageGen1__Publisher
              value: {{ .Values.config.gen2BatchImagePublisher }}
            - name: BatchImageGen1__Sku
              value: {{ .Values.config.gen2BatchImageSku | quote }}
            - name: BatchImageGen2__Version
              value: {{ .Values.config.gen2BatchImageVersion }}
            - name: BatchImageGen1__Offer
              value: {{ .Values.config.gen1BatchImageOffer }}
            - name: BatchImageGen1__Publisher
              value: {{ .Values.config.gen1BatchImagePublisher }}
            - name: BatchImageGen1__Sku
              value: {{ .Values.config.gen1BatchImageSku | quote }}
            - name: BatchImageGen1__Version
              value: {{ .Values.config.gen1BatchImageVersion }}
            - name: BatchNodeAgentSkuId
              value: {{ .Values.config.batchNodeAgentSkuId }}
            - name: BatchScheduling__PoolRotationForcedDays
              value: {{ .Values.config.batchPoolRotationForcedDays | quote }}
            - name: BatchScheduling__Prefix
              value: {{ .Values.config.batchPrefix | quote }}
            - name: Martha__Url
              value: {{ .Values.config.marthaUrl }}
            - name: Martha__KeyVaultName
              value: {{ .Values.config.marthaKeyVaultName }}
            - name: Martha__SecretName
              value: {{ .Values.config.marthaSecretName }}
            - name: BatchScheduling__UsePreemptibleVmsOnly
              value: {{ .Values.config.usePreemptibleVmsOnly | quote}}
            - name: BatchNodes__GlobalStartTask
              value: {{ .Values.config.globalStartTaskPath }}
            - name: BatchNodes__GlobalManagedIdentity
              value: {{ .Values.config.batchManagedIdentity }}
            - name: Storage__ExternalStorageContainers
{{- $containers  := list -}}
{{- range .Values.externalSasContainers }}
{{- $containers = append $containers (printf "https://%s.blob.core.windows.net/%s?%s" .accountName .containerName .sasToken) -}}
{{- end }}
              value: {{ join ";" $containers}}
          image: {{ .Values.images.tes }}
          name: tes
          ports:
            - containerPort: {{ .Values.service.tesPort }}
          resources:
            requests:
              cpu: "1.5"
              memory: "3072Mi"
            limits:
              cpu: "8.0"
              memory: "8192Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
status: {}
