name: dotnet restore/build/test (root)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Delete nuget.config
      run: rm nuget.config
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: sudo dotnet test --no-build --verbosity normal --filter "TestCategory=RequiresRoot" --logger "console;verbosity=detailed"
